### PR TITLE
Fix undefined method in TCP socket

### PR DESCRIPTION
**Pull request by Neznauy**
Hi! 
Problem ```undefined method 'sock' for Yabeda::Puma::Plugin::Statistics::Fetcher::Class``` appeared after update to 0.2.0 version. Seems like it is because of initialization ```Socket``` in variable.
Linked with https://github.com/yabeda-rb/yabeda-puma-plugin/issues/6

### CODE REVIEW

**Comment by Envek** [comment]
Thank you very much! Released as [0.2.1](https://rubygems.org/gems/yabeda-puma-plugin/versions/0.2.1)
